GuessEv/config/routes.rb
GuessEv::Application.routes.draw do
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  match "/titles/edit" => "titles#edit",   :via => :get
  match "/titles/edit" => "titles#update", :via => :put

  match "/users/todaytitle" => "users#todaytitle", :constraints => { :id => /[0-9]+/ }
  match "/users/showranking" => "users#showranking"
  match "/users/showpreviousheadlines" => "users#showpreviousheadlines"

  devise_for :users, :controllers => {:sessions => 'devise:sessions'}, :skip => [:sessions] do
    get 'login'   => 'devise/sessions#new',         :as => :new_user_session         
    post 'login'  => 'devise/sessions#create',      :as => :user_session          
    get 'logout'  => 'devise/sessions#destroy',     :as => :destroy_user_sessions
    delete 'logout'  => 'devise/sessions#destroy', :as => :destroy_user_sessions
    get 'signup'  => 'devise/registrations#new',    :as => :new_user_account
    post 'signup' => 'devise/registrations#create', :as => :user_account
  end

  root :to => 'titles#index'

  resources :titles
  resources :users, :only => [:new, :create, :show, :edit, :update, :destroy]

end

GuessEv/app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

GuessEv/app/models/keyword.rb
class Keyword < ActiveRecord::Base

has_and_belongs_to_many :titles

end

GuessEv/app/models/super_user.rb
class SuperUser < User

end

GuessEv/app/models/superuser.rb
class SuperUser < User

end

GuessEv/app/models/title.rb
class Title < ActiveRecord::Base

has_and_belongs_to_many :keywords
belongs_to :user

require 'open-uri'
require 'json'
require 'nokogiri'

validates :name, :presence => true
validates :user_id, :presence => true
validate :duplicatePostsCheck

after_create :create_keywords


def duplicatePostsCheck
	todayTitlesOfUser = self.user.getTodayUserTitle

	unless todayTitlesOfUser.empty?
		if self.id == todayTitlesOfUser.first.id
			return
		else
			errors.add :name,  "User #{self.user_id} has already posted today"
		end
	end
end



#At Title creation
#Create splitted keywords from the new title
def create_keywords
	@title_to_parse = self.name
	keywordsArray = parseTitles @title_to_parse
	keywordsArray.each do |t|
		dateEndInterval = User.dateEndInterval
		keyw = Keyword.where(:created_at => dateEndInterval-1.day..dateEndInterval, :name => t)
		if !keyw.empty?
			keyw.first.increment(:count)
			keyw.first.save
			self.keywords << keyw
			self.save
		else
			self.keywords.create :name => t, :count => 1
		end
	end
end

#Parse a Title and split it in an array conataining words longer than 3
def parseTitles(titleToParse)
	splittedTitle = titleToParse.split
	res = []
	splittedTitle.each do |t|
		if t.size > 3
			res << t
		end
	end
	return res
end

#Gets the Evening Standard latest Headline
def self.getESTitle
	rssSrc = Nokogiri::HTML(open("http://standardonline.newspaperdirect.com/epaper/services/rss.ashx?cid=1237&type=full"))
	pRSS = rssSrc.xpath('//item/title')
	esTitle = pRSS.first.text
	#Parsed text is "DD/MM/YYYY: FRONT PAGE: TITLE IS HERE"
	#Need to get rid of the 24 first chars
	esTitle = esTitle.last(esTitle.length - 24)
end

def self.getTwitterTrends
	tweet_trends = []
	jsonSrc = JSON.parse(open("http://api.twitter.com/1/trends/44418.json").read)
	jsonSrc.first["trends"].each do |p|
		tweet_trends << p["name"]
	end
	return tweet_trends
end

def calculateRanking

	answer_keywords = SuperUser.first.getTodayUserTitle.first.id

end

end

GuessEv/app/models/user.rb
class User < ActiveRecord::Base
  
has_many :titles

after_destroy :deleteTitles

scope :standard, where(:type => 'User')
scope :super, where(:type => 'SuperUser')

# Include default devise modules. Others available are:
# :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable 
devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable

# Setup accessible (or protected) attributes for your model
attr_accessible :email, :password, :password_confirmation, :remember_me

	def getTodayUserTitle
		dateEndInterval = User.dateEndInterval
		return self.titles.where(:created_at => dateEndInterval-1.day..dateEndInterval)
	end

	def hasCurrentTitle?
		if self.getTodayUserTitle.nil?
			return false
		else 
			return true
		end
	end

	def deleteTitles
		p = self.getTodayUserTitle
		if !p.empty?
			p.first.keywords.each do |k|
				k.count = k.count - 1
			end
		end
		self.titles.destroy_all
	end

	def self.dateEndInterval
		#GuessEv::Application.RESTART_TIME_HOUR
		if DateTime.now.hour > 18
			dateEndInterval = DateTime.civil(DateTime.now.year, DateTime.now.month, DateTime.now.day+1, 18 , 0, 0, Rational(0, 24))
		else
			dateEndInterval = DateTime.civil(DateTime.now.year, DateTime.now.month, DateTime.now.day, 18 , 0, 0, Rational(0, 24))
		end
		return dateEndInterval
	end

	def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
	  data = access_token.extra.raw_info
	  if user = User.where(:email => data.email).first
	    user
	  else # Create a user with a stub password. 
	    User.create!(:email => data.email, :password => Devise.friendly_token[0,20]) 
	  end
	end

	def self.find_for_open_id(access_token, signed_in_resource=nil)
	  data = access_token.info
	  if user = User.where(:email => data["email"]).first
	    user
	  else
	    User.create!(:email => data["email"], :password => Devise.friendly_token[0,20])
	  end
	end
end

GuessEv/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

GuessEv/app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    # You need to implement the method below in your model
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def google
      @user = User.find_for_open_id(request.env["omniauth.auth"], current_user)

      if @user.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
        sign_in_and_redirect @user, :event => :authentication
      else
        session["devise.google_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
  end

end

GuessEv/app/controllers/titles_controller.rb
class TitlesController < ApplicationController

layout 'main'

def index
	p = SuperUser.first
	#Instanciate object for creation
	@title = Title.new

	#Gets the 5 last super user headlines
	@title_historic = p.titles.last(5)

	#Gets the 10 twitter trend
	@tweet_trends = Title.getTwitterTrends

	if user_signed_in?
		p = current_user.getTodayUserTitle
		if p.empty?
			@today_title = nil
		else
			@today_title = p.first.name
		end
	else
		@today_title = nil
	end
end

def create
	@user = current_user
	@title = @user.titles.build(:name => params[:title][:name])
	unless @user.save
		render 'index'
	return
	end 
	flash[:notice] = "Title created"
	redirect_to '/users/todaytitle'
end

def edit
	@title = Title.new

	p = current_user.getTodayUserTitle
	@today_title = p.first.name
end

def update
	p = current_user.getTodayUserTitle
	p.first.name = params[:title][:name]
	p.first.save!
	redirect_to '/users/todaytitle'
end

end

GuessEv/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  	layout 'main'

	def todaytitle
		p = current_user.getTodayUserTitle
		@today_title = p.first.name
	end

	def showpreviousheadlines
		@previous_headlines = current_user.titles.last(5).reverse
	end

	def show
		begin
			@current_user ||= User.find(params[:id])
			@previous_headlines = current_user.titles.last(5).reverse
		rescue
			redirect_to "/", :flash => { :error => "User doesn't exist" }
		end
	end
end

GuessEv/app/helpers/application_helper.rb
module ApplicationHelper

end

GuessEv/app/helpers/home_helper.rb
module HomeHelper
end

GuessEv/app/helpers/keyword_helper.rb
module KeywordHelper
end

GuessEv/app/helpers/super_users_helper.rb
module SuperUsersHelper
end

GuessEv/app/helpers/title_helper.rb
module TitleHelper

end

GuessEv/app/views/home/index.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">
<HTML>
   <HEAD>
      <TITLE>Home page</TITLE>

   </HEAD>
   <BODY>

   	<h1>Home page</h1>

	<%= form_for @title do |f| %>
  		<%= f.text_field :title %>
  		<%= f.submit "Post" %>
	<% end %>
      
   </BODY>
</HTML>

GuessEv/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GuessEv</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

GuessEv/app/views/layouts/main.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">
<HTML>
  <HEAD>
    <TITLE>Title page</TITLE>

    <%= stylesheet_link_tag "bootstrap" %>

  </HEAD>
  
  <BODY>
  <div class="container">

  <% if flash[:error] %>
     <div class="alert alert-error"> <%= flash[:error] %> </div>
  <% end %>

  <br><%= render "shared/topbar" %> </br>
  <br> <%= render "shared/logger" %> </br>

  <h1> Guess evening standard </h1>

  <%= yield -%>

  </div>   
  </BODY>
</HTML>

GuessEv/app/views/shared/_logger.html.erb
    <table>
    <tr>
      <td>
      <% if user_signed_in?  %>
        Signed in as <%= current_user.email %>
      <% else %>
        <%= form_for "user", :url => user_session_path, :html => {:class => "well form-inline"} do |f| %>
        <div>
        Login:
        <%= f.text_field :email, :class => "input-small", :placeholder => "email" %>
        Password:
        <%= f.password_field :password, :class => "input-small", :placeholder => "password" %>
        <%= f.check_box :remember_me %>
        <%= f.label :remember_me, :class => "checkbox" %>
        <%= f.submit 'Sign in', :class => "btn" %>
        <%= link_to "Forgot your password?", new_password_path('user') %>
        </div>
        <div>
          <br/>
          <%= link_to image_tag("fb.png", :width => "125", :height => "75"), user_omniauth_authorize_path(:facebook) %>
          <%= link_to image_tag("google.png", :width => "125", :height => "75"), user_omniauth_authorize_path(:google) %>
        </div>
        <% end %> 
      <% end %>
      </td>
      <td>
        <% if user_signed_in?  %>
          <%= link_to "logout", destroy_user_sessions_path, :method => :get %>
        <% end %>  
      </td>
    </tr>
    <% if !user_signed_in? %>
    <tr>
        Not registered? What a shame!!
        <%= link_to 'Sign up right now!', new_user_registration_path%>
    </tr>
    <% end %>
    </table>

GuessEv/app/views/shared/_menu.html.erb
 <%= link_to "Ranking", "users/showranking" %>

<% if user_signed_in?  %>
  <%= link_to "My heandlines", "users/showpreviousheadlines" %>
<% end %>  

GuessEv/app/views/shared/_topbar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
      <div class="container">
        <h3><a class="brand" href="/"> TMW</a></h3>
        <ul class="nav">
            <li><%= link_to "Ranking", "/users/showranking" %></li>
            <% if user_signed_in? %>
            <li><%= link_to "My heandlines", "/users/showpreviousheadlines" %></li>
            <% end %> 
        </ul>
      </div>
  </div>
</div>

GuessEv/app/views/titles/edit.html.erb
<h2> Edit your today's headline </h2>

<div class="well">
Previous headline: <%= @today_title %>
      
<%= form_for @title, :url => {:action => "edit"}, :html => {:method => "put", :class => "form-horizontal"}  do |f| %>
  <div class ="input-append">
    <%= f.text_field :name %>
    <%= f.submit "Edit",:class => "btn", :type => "submit",:method => "post" %>
  </div> 
<% end %>
</div>





  

GuessEv/app/views/titles/index.html.erb
<% [:info, :error].each do |key| %>
  <% if flash[key] %>
  <div class="<%= key %>" id="flash">
    <%= flash[key] %>
  </div>
  <% end %>
<% end %>

<div>
  <% if @title.errors.any?  %>
    <%= @title.errors.messages[:name] %>
  <% end %>   
</div>

<div class="well">
  <% if @today_title.nil? %>
    <%= form_for @title,:url => {:action => "create"}, :html => {:class => "form-horizontal"} do |f| %>
    <div class="input-append">
      <%= f.text_field :name,:id => "appendedPrependedInput",:size => "30", :placeholder => "Place your guess...", :type => "text" %>
      <%= f.submit "Post", :class => "btn", :type => "submit",:method => "post" %>
    </div> 
    <% end %>
  <% else %>
    <%= @today_title %>
    <%= link_to "Edit", "/titles/edit", :class => "btn btn-primary" %>
    <!--<a data-toggle="modal" href="#myModal" class="btn btn-primary btn-large">Launch demo modal</a>  -->
  <% end %>
</div> 

<div>
  <h2> Need inspiration? </h2>
  <h3> Latest headlines </h3>

  <table>
    <% @title_historic.reverse.each do |p| %>
      <tr>
        <td>  <%= p.created_at.to_date %> </td>
        <td>  <%= p.name %> </td>
      </tr>
    <% end %>
  </table>

  <h3> Twitter trends </h3>

  <table>
    <% @tweet_trends.each do |p| %>
      <tr>
        <td>  <%= p %> </td>
      </tr>
    <% end %>
  </table>        
</div>

<!--
<div id="myModal" class="modal">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    <h3>Modal Heading</h3>
  </div>
  <div class="modal-body">
    <h4>Text in a modal</h4>
    <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem.</p>

    <h4>Popover in a modal</h4>
    <p>This <a href="#" class="btn popover-test" data-content="And here's some amazing content. It's very engaging. right?" data-original-title="A Title">button</a> should trigger a popover on hover.</p>

    <h4>Tooltips in a modal</h4>
    <p><a href="#" class="tooltip-test" data-original-title="Tooltip">This link</a> and <a href="#" class="tooltip-test" data-original-title="Tooltip">that link</a> should have tooltips on hover.</p>

  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="alert">Close</a>
    <a href="#" class="btn btn-primary">Save changes</a>
  </div>
</div>
!-->

<script src="assets/js/bootstrap-modal.js"></script>

GuessEv/app/views/users/show.html.erb
<h2> <%= @current_user.email%>'s headlines </h2>
     	
<table>
  <% @previous_headlines.each do |p| %>
    <tr>
      <td>  <%= p.created_at.to_date %> </td>
      <td>  <%= p.name %> </td>
    </tr>
  <% end %>
</table>

GuessEv/app/views/users/showpreviousheadlines.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">
<HTML>
   <HEAD>
      <TITLE>My page</TITLE>

   </HEAD>
   <BODY>

     <%= render "shared/logger" %> 

    <h1> Guess evening standard </h1>

   	<h2> Your last headlines </h2>
   	
   	<table>
        <% @previous_headlines.each do |p| %>
        <tr>
          <td>  <%= p.created_at.to_date %> </td>
          <td>  <%= p.name %> </td>
        </tr>
        <% end %>
    </table>

   </BODY>
</HTML>

GuessEv/app/views/users/showranking.html.erb
<h2> Rankings </h2>

<table>
   <tr>
   	<td> #1 </td>
   </tr>
   <tr>
   	 <td> #2 </td>
   </tr>
</table>

GuessEv/app/views/users/todaytitle.html.erb
<h2> My today's headline </h2>

<%= @today_title %>
<%= link_to "Edit", "/titles/edit" %>
     
<h3> Some statistics </h3>